//#include "v_current/ThostFtdcTraderApi.h"
//#include "v_current/ThostFtdcMdApi.h"
//#include "ctp_6.7.7/linux/ThostFtdcTraderApi.h"
//#include "ctp_6.7.7/linux/ThostFtdcMdApi.h"
#include "ctp_6.7.7/macos/thosttraderapi_se.framework/Versions/A/Headers/ThostFtdcTraderApi.h"
#include "ctp_6.7.7/macos/thostmduserapi_se.framework/Versions/A/Headers/ThostFtdcMdApi.h"
